repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
        - id: check-merge-conflict
    - repo: local
      hooks:
        - id: black
          name: black
          entry: env -C drf_learner poetry run black .
          language: system
          always_run: true
          pass_filenames: false
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: env -C drf_learner pylint app
          language: system
          always_run: true
          pass_filenames: false